---
- name: Deploy Dashy App
  hosts: all
  become: true
  roles:
    - geerlingguy.docker
  tasks:          
    - name: Build the app with docker
      command: docker run -d -p 80:80 -p 443:443 linuxserver/heimdall:latest
      ignore_errors: true


    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/nephila/homarr
        state: directory
        mode: '0755'
    
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/nephila/homarr/configs
        state: directory
        mode: '0755'

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/nephila/homarr/icons
        state: directory
        mode: '0755'

    - name: Stop a container
      command: docker stop homarr
      
    - name: Build the app with docker
      command: docker run  --restart always -d -e EDIT_MODE_PASSWORD=UnsafestPasswordEver --name homarr --restart unless-stopped  -p 7575:7575  -v /home/nephila/homarr/configs:/app/data/configs  -v /home/nephila/homarr/icons:/app/public/icons  -d ghcr.io/ajnart/homarr:latest
        
    - name: Open port in the firewall
      ufw:
        rule: allow
        port: "7575"
      
        
#    - name: "Install forever (to run Node.js app)."
#      npm: name=forever global=yes state=present
    
 #   - name: "Check list of Node.js apps running."
 #     command: forever list
#      register: forever_list
#      changed_when: false
    
#    - name: "Start example Node.js app."
#      command: forever start  /home/nephila/dashy/server.js
#      when: "forever_list.stdout.find('/path/to/app.js') == -1"
