---
- name: Deploy Dashy App
  hosts: all
  become: true
  roles:
    - geerlingguy.docker
  tasks:          
    - name: Build the app with docker
      command: docker run -d -p 80:80 -p 443:443 linuxserver/heimdall:latest
        
    - name: Open port in the firewall
      ufw:
        rule: allow
        port: "80"

    - name: Open port in the firewall
      ufw:
        rule: allow
        port: "443"
      
        
#    - name: "Install forever (to run Node.js app)."
#      npm: name=forever global=yes state=present
    
 #   - name: "Check list of Node.js apps running."
 #     command: forever list
#      register: forever_list
#      changed_when: false
    
#    - name: "Start example Node.js app."
#      command: forever start  /home/nephila/dashy/server.js
#      when: "forever_list.stdout.find('/path/to/app.js') == -1"
