---
- name: Deploy Dashy App
  hosts: all
  become: true
  roles:
    - geerlingguy.docker
  tasks:
    - name: Clone Dashy repository
      git:
        repo: https://github.com/Lissy93/dashy.git
        dest: /home/nephila/dashy  
          
      
    - name: Build the app with docker
      command: docker run -d -p 4000:80 --restart=always lissy93/dashy:latest
      args:
        chdir: /home/nephila/dashy
        
    - name: Open port in the firewall
      ufw:
        rule: allow
        port: "4000"
      
        
#    - name: "Install forever (to run Node.js app)."
#      npm: name=forever global=yes state=present
    
 #   - name: "Check list of Node.js apps running."
 #     command: forever list
#      register: forever_list
#      changed_when: false
    
#    - name: "Start example Node.js app."
#      command: forever start  /home/nephila/dashy/server.js
#      when: "forever_list.stdout.find('/path/to/app.js') == -1"
